import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import { CheckCircle2, ClipboardCheck, Plus, Printer, RefreshCw, ShieldCheck, Wrench, X } from "lucide-react";
import { Link } from "react-router-dom";
import api from "@/services/api";
import { useToast } from "@/context/toastContext";
import { printCanaDocument } from "@/modules/management/utils/printCanaDocument";

type View = "overview" | "cleaning" | "maintenance" | "safety";
type Equipment = { _id: string; name: string; code: string };
type RecordItem = { _id: string; recordNo: string; category: string; title: string; area?: string; scheduledDate?: string; completedDate?: string; responsible?: string; details?: string; correctiveAction?: string; status: "open" | "completed" | "verified" | "closed"; equipment?: Equipment | null };
type Staff = { _id: string; fullName: string; role: string; status: string };
const names: Record<View, string> = { overview: "Factory compliance", cleaning: "Cleaning register", maintenance: "Maintenance register", safety: "Safety register" };
const categoryFor: Partial<Record<View, string>> = { cleaning: "cleaning", maintenance: "maintenance" };
const safetyCategories = ["inspection", "incident", "training", "ppe"];
const label = (value: string) => value.replaceAll("_", " ");
const statusStyle: Record<RecordItem["status"], string> = { open: "bg-amber-50 text-amber-700", completed: "bg-slate-100 text-slate-700", verified: "bg-emerald-50 text-emerald-700", closed: "bg-slate-100 text-slate-500" };

export default function FactoryCompliancePage({ view = "overview" }: { view?: View }) {
  const { toast } = useToast(); const [records, setRecords] = useState<RecordItem[]>([]); const [equipment, setEquipment] = useState<Equipment[]>([]); const [staff, setStaff] = useState<Staff[]>([]); const [status, setStatus] = useState("all"); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const category = categoryFor[view];
  const load = async () => { setError(""); try { const [recordsData, equipmentData, staffData] = await Promise.all([api.get<{ data: RecordItem[] }>(category ? `/compliance/records?category=${category}` : "/compliance/records"), api.get<{ data: Equipment[] }>("/compliance/equipment"), api.get<{ data: Staff[] }>("/users")]); setRecords(recordsData.data.data || []); setEquipment(equipmentData.data.data || []); setStaff((staffData.data.data || []).filter((item) => item.role !== "customer" && item.status === "active")); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load factory records."); } };
  useEffect(() => { void load(); }, [category]);
  const visible = useMemo(() => { const source = view === "safety" ? records.filter((item) => safetyCategories.includes(item.category)) : records; return status === "all" ? source : source.filter((item) => item.status === status); }, [records, status, view]);
  const complete = async (record: RecordItem) => { try { await api.patch(`/compliance/records/${record._id}`, { status: record.status === "open" ? "completed" : "verified", completedDate: record.completedDate || new Date().toISOString().slice(0, 10) }); toast(record.status === "open" ? "Record completed." : "Record verified.", "success"); void load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update record."); } };
  const print = () => printCanaDocument({ title: `${names[view]} register`, reference: `FCR-${new Date().toISOString().slice(0, 10).replaceAll("-", "")}`, status: "Official factory register", details: [{ label: "Register", value: names[view] }, { label: "Records", value: String(visible.length) }], table: { headers: ["Reference", "Type", "Activity", "Area / equipment", "Responsible", "Date", "Status"], rows: visible.map((item) => [item.recordNo, label(item.category), item.title, item.area || item.equipment?.name || "—", item.responsible || "—", item.completedDate || item.scheduledDate || "—", label(item.status)]) } });
  const counts = { open: records.filter((item) => item.status === "open").length, pending: records.filter((item) => item.status === "completed").length, verified: records.filter((item) => ["verified", "closed"].includes(item.status)).length };
  return <div className="mx-auto max-w-7xl space-y-4"><header className="flex flex-col justify-between gap-3 border-b border-slate-200 pb-4 sm:flex-row sm:items-center"><div><p className="cana-section-kicker">Factory records</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight text-slate-950">{names[view]}</h1></div><div className="flex flex-wrap gap-2"><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-bold text-slate-700"><RefreshCw size={15} />Refresh</button>{view !== "overview" && <><button onClick={print} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-bold text-slate-700"><Printer size={15} />Print</button><button onClick={() => setOpen(true)} className="inline-flex items-center gap-2 rounded-lg bg-slate-950 px-3 py-2 text-sm font-bold text-white"><Plus size={16} />Add record</button></>}</div></header>{error && <p className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}{open && <RecordModal view={view} equipment={equipment} staff={staff} onClose={() => setOpen(false)} onSaved={() => { setOpen(false); void load(); }} />}{view === "overview" ? <Overview counts={counts} recent={records.slice(0, 8)} /> : <><section className="cana-panel flex flex-wrap items-center justify-between gap-3 p-3"><p className="text-sm text-slate-600">Open → complete → verify</p><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700"><option value="all">All statuses</option><option value="open">Open</option><option value="completed">Awaiting verification</option><option value="verified">Verified</option></select></section><Records records={visible} onComplete={complete} /></>}</div>;
}
function Overview({ counts, recent }: { counts: { open: number; pending: number; verified: number }; recent: RecordItem[] }) { return <><section className="grid gap-3 sm:grid-cols-3"><Metric label="Open actions" value={counts.open} /><Metric label="Awaiting verification" value={counts.pending} /><Metric label="Verified records" value={counts.verified} /></section><section className="grid gap-3 md:grid-cols-3"><Module to="/management/compliance/cleaning" icon={ClipboardCheck} title="Cleaning" text="Daily cleaning and hygiene records." /><Module to="/management/compliance/maintenance" icon={Wrench} title="Maintenance" text="Service, repair, and follow-up records." /><Module to="/management/compliance/safety" icon={ShieldCheck} title="Safety" text="Inspections, incidents, PPE, and training." /></section><section className="cana-panel overflow-hidden"><div className="border-b border-slate-100 px-4 py-3"><h2 className="font-extrabold text-slate-950">Recent records</h2></div><Records records={recent} onComplete={() => undefined} readOnly /></section></>; }
function Metric({ label: text, value }: { label: string; value: number }) { return <article className="cana-panel p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{text}</p><p className="mt-1 text-2xl font-extrabold text-slate-950">{value}</p></article>; }
function Module({ to, icon: Icon, title, text }: { to: string; icon: typeof ShieldCheck; title: string; text: string }) { return <Link to={to} className="cana-panel p-4 transition hover:border-slate-400"><Icon size={18} className="text-slate-700" /><h2 className="mt-3 font-extrabold text-slate-950">{title}</h2><p className="mt-1 text-sm text-slate-500">{text}</p></Link>; }
function Records({ records, onComplete, readOnly = false }: { records: RecordItem[]; onComplete: (record: RecordItem) => void; readOnly?: boolean }) { return <section className="cana-panel overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Record</th><th className="px-4 py-3">Area</th><th className="px-4 py-3">Responsible</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Status</th>{!readOnly && <th className="px-4 py-3"></th>}</tr></thead><tbody className="divide-y divide-slate-100">{records.map((item) => <tr key={item._id}><td className="px-4 py-3"><p className="font-bold text-slate-950">{item.title}</p><p className="text-xs text-slate-500">{item.recordNo} · {label(item.category)}</p></td><td className="px-4 py-3 text-slate-600">{item.area || item.equipment?.name || "—"}</td><td className="px-4 py-3 text-slate-600">{item.responsible || "—"}</td><td className="px-4 py-3 text-slate-600">{item.completedDate || item.scheduledDate || "—"}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusStyle[item.status]}`}>{label(item.status)}</span></td>{!readOnly && <td className="px-4 py-3">{!["verified", "closed"].includes(item.status) && <button onClick={() => onComplete(item)} className="inline-flex items-center gap-1 text-xs font-bold text-slate-700"><CheckCircle2 size={14} />{item.status === "open" ? "Complete" : "Verify"}</button>}</td>}</tr>)}{!records.length && <tr><td colSpan={readOnly ? 5 : 6} className="px-4 py-10 text-center text-sm text-slate-500">No records yet.</td></tr>}</tbody></table></section>; }
function RecordModal({ view, equipment, staff, onClose, onSaved }: { view: View; equipment: Equipment[]; staff: Staff[]; onClose: () => void; onSaved: () => void }) { const { toast } = useToast(); const [error, setError] = useState(""); const recordCategory = categoryFor[view] || "inspection"; const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); try { await api.post("/compliance/records", Object.fromEntries(new FormData(event.currentTarget))); toast("Factory record saved.", "success"); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save record."); } }; return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form onSubmit={submit} className="w-full max-w-xl rounded-xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 className="font-extrabold text-slate-950">Add {names[view]}</h2><button type="button" onClick={onClose} className="rounded-lg border border-slate-300 p-2"><X size={16} /></button></div><div className="grid gap-3 p-5 sm:grid-cols-2">{error && <p className="sm:col-span-2 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}{view === "safety" ? <Field label="Record type"><select name="category" defaultValue="inspection">{safetyCategories.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></Field> : <input type="hidden" name="category" value={recordCategory} />}<Field label="Activity"><input required name="title" placeholder="What was done or found" /></Field><Field label="Area"><input name="area" placeholder="Factory area" /></Field><Field label="Equipment"><select name="equipment"><option value="">Not applicable</option>{equipment.map((item) => <option key={item._id} value={item._id}>{item.code} · {item.name}</option>)}</select></Field><Field label="Date"><input name="scheduledDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} /></Field><Field label="Responsible staff"><select required name="responsible" defaultValue=""><option value="" disabled>Select staff</option>{staff.map((item) => <option key={item._id} value={item.fullName}>{item.fullName}</option>)}</select></Field><Field label="Details"><textarea name="details" rows={2} /></Field><Field label="Corrective action"><textarea name="correctiveAction" rows={2} /></Field></div><div className="flex justify-end gap-2 border-t border-slate-200 px-5 py-4"><button type="button" onClick={onClose} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold text-slate-700">Cancel</button><button className="rounded-lg bg-slate-950 px-3 py-2 text-sm font-bold text-white">Save record</button></div></form></div>; }
function Field({ label: text, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-bold text-slate-700">{text}<span className="mt-1 block [&_input]:h-10 [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:border-slate-200 [&_input]:px-3 [&_select]:h-10 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:border-slate-200 [&_select]:bg-white [&_select]:px-3 [&_textarea]:w-full [&_textarea]:rounded-lg [&_textarea]:border [&_textarea]:border-slate-200 [&_textarea]:p-3">{children}</span></label>; }
