import { Router } from "express";
import mongoose from "mongoose";
import PurchaseOrder from "../purchaseOrders/purchaseOrder.model";
import SupplierPayment from "./supplierPayment.model";

const router = Router();
router.get("/", async (_req, res, next) => { try { const data = await SupplierPayment.find().populate("supplier", "name code").populate("purchaseOrder", "poNumber total").sort({ paidAt: -1 }).lean(); res.json({ data }); } catch (error) { next(error); } });
router.post("/", async (req, res, next) => { try { const { supplier, purchaseOrder, amount, method, chequeNumber, bankName, chequeDate, reference, paidAt, notes } = req.body || {}; if (!mongoose.Types.ObjectId.isValid(supplier) || !mongoose.Types.ObjectId.isValid(purchaseOrder)) throw new Error("Select a supplier and purchase order."); if (!Number.isFinite(Number(amount)) || Number(amount) <= 0) throw new Error("Payment amount must be greater than zero."); if (!["cash", "bank_transfer", "bank_cheque", "mobile_money", "other"].includes(method)) throw new Error("Select a valid payment method."); if (method === "bank_cheque" && (!String(chequeNumber || "").trim() || !String(bankName || "").trim())) throw new Error("Cheque number and bank name are required for a bank cheque."); const po = await PurchaseOrder.findById(purchaseOrder).lean(); if (!po || String(po.supplier) !== String(supplier)) throw new Error("The selected purchase order does not belong to this supplier."); if (!["received", "partially_received"].includes(po.status)) throw new Error("Receive the raw materials before recording a supplier payment."); const paid = await SupplierPayment.aggregate([{ $match: { purchaseOrder: new mongoose.Types.ObjectId(purchaseOrder) } }, { $group: { _id: null, total: { $sum: "$amount" } } }]); if (Number(amount) > Number(po.total || 0) - Number(paid[0]?.total || 0) + 0.0001) throw new Error("Payment cannot exceed the remaining purchase-order balance."); const paymentNumber = `SPY-${new Date().getFullYear()}-${String((await SupplierPayment.countDocuments()) + 1).padStart(5, "0")}`; const payment = await SupplierPayment.create({ paymentNumber, supplier, purchaseOrder, amount: Number(amount), method, chequeNumber, bankName, chequeDate: chequeDate || undefined, reference, paidAt: paidAt || new Date(), notes }); res.status(201).json({ data: await SupplierPayment.findById(payment._id).populate("supplier", "name code").populate("purchaseOrder", "poNumber total").lean() }); } catch (error) { next(error); } });
export default router;
