import { ArrowUpRight, Mail, MapPin, Phone } from "lucide-react";
import { FaFacebookF, FaInstagram, FaLinkedinIn, FaWhatsapp, FaXTwitter, FaYoutube } from "react-icons/fa6";
import { Link } from "react-router-dom";
import logo from "@/assets/logocanan.png";

const socials = [{ label: "Facebook", href: "https://www.facebook.com/canapaints.cbg", icon: FaFacebookF }, { label: "Instagram", href: "https://www.instagram.com/canapaints.cbg/", icon: FaInstagram }, { label: "X", href: "https://x.com/canapaints_cbg", icon: FaXTwitter }, { label: "LinkedIn", href: "https://www.linkedin.com/company/canapaints-cbg/", icon: FaLinkedinIn }, { label: "YouTube", href: "https://www.youtube.com/@canapaints.cbg", icon: FaYoutube }, { label: "WhatsApp", href: "https://wa.me/250789408367", icon: FaWhatsapp }];

export default function Footer() { const year = new Date().getFullYear(); return <footer className="border-t border-neutral-800 bg-neutral-950 text-white"><div className="mx-auto max-w-7xl px-5 py-10 sm:px-8 sm:py-12 lg:px-8 lg:py-14"><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-[1.35fr_.75fr_.9fr_1.05fr] lg:gap-10"><div className="sm:col-span-2 lg:col-span-1"><Link to="/" className="inline-flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-white p-1.5"><img src={logo} alt="CANAN Business Group" className="h-full w-full object-contain" /></span><span><span className="block text-xl font-extrabold tracking-tight">CANA</span><span className="block text-[9px] font-bold uppercase tracking-[.16em] text-white/50">CANAN Business Group Ltd</span></span></Link><p className="mt-5 max-w-sm text-sm leading-6 text-white/60">Paint products and practical site services for projects across Rwanda.</p><div className="mt-5 flex flex-wrap gap-2">{socials.map(({ label, href, icon: Icon }) => <a key={label} href={href} target="_blank" rel="noreferrer" aria-label={label} className="flex h-9 w-9 items-center justify-center rounded-lg border border-white/10 text-white/65 transition hover:border-red-600 hover:bg-red-700 hover:text-white"><Icon size={15} /></a>)}</div></div><FooterGroup title="Company"><FooterLink to="/">Home</FooterLink><FooterLink to="/about">About</FooterLink><FooterLink to="/team">Our team</FooterLink><FooterLink to="/projects">Projects</FooterLink><FooterLink to="/contact">Contact</FooterLink></FooterGroup><FooterGroup title="Solutions"><FooterLink to="/cana-paints/products">Paint products</FooterLink><FooterLink to="/cana-paints/painting-services">Painting services</FooterLink><FooterLink to="/cana-paints/estimate-cost">Paint estimator</FooterLink><FooterLink to="/cana-services/scaffolds">Scaffold rental</FooterLink><FooterLink to="/cana-services/transport">Transport</FooterLink></FooterGroup><div className="rounded-2xl border border-white/10 bg-white/[.035] p-4 sm:p-5"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-white/50">Contact</p><div className="mt-4 space-y-3"><ContactRow icon={MapPin} text="Remera, Kwa Rwahama · Kigali" /><ContactRow icon={Phone} text="+250 789 408 367" href="tel:+250789408367" /><ContactRow icon={Mail} text="info@cana.rw" href="mailto:info@cana.rw" /></div><Link to="/contact" className="mt-5 inline-flex h-10 items-center gap-1 rounded-lg bg-white px-3 text-sm font-bold text-slate-950 transition hover:bg-red-700 hover:text-white">Contact CANA <ArrowUpRight size={15} /></Link></div></div></div><div className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-5 py-4 text-xs font-medium text-white/45 sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-8"><span>© {year} CANAN Business Group Ltd. All rights reserved.</span><span>Kigali, Rwanda</span></div></div></footer>; }
function FooterGroup({ title, children }: { title: string; children: React.ReactNode }) { return <div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-white/50">{title}</p><div className="mt-4 flex flex-col gap-2.5">{children}</div></div>; }
function FooterLink({ to, children }: { to: string; children: React.ReactNode }) { return <Link to={to} className="w-fit text-sm font-semibold text-white/70 transition hover:text-red-400">{children}</Link>; }
function ContactRow({ icon: Icon, text, href }: { icon: typeof MapPin; text: string; href?: string }) { const content = <><Icon size={15} className="mt-0.5 shrink-0 text-red-400" /><span>{text}</span></>; return href ? <a href={href} className="flex gap-2 text-sm font-semibold text-white/75 transition hover:text-white">{content}</a> : <p className="flex gap-2 text-sm font-semibold text-white/75">{content}</p>; }
