import { useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import { Banknote, Send } from "lucide-react";
import api from "@/services/api";
import { useAuth } from "@/context/authContext";
import { useToast } from "@/context/toastContext";

type Payment = { _id: string; kind: "salary" | "advance"; amount: number; grossAmount?: number; advanceDeduction?: number; period?: string; reason?: string; status: string; staff?: { fullName: string } };
type Staff = { _id: string; fullName: string; role: string; status: string; baseSalary?: number };
const money = (value: number) => `${value.toLocaleString("en-RW")} RWF`;
export default function StaffPaymentsPage() {
  const { user } = useAuth(); const { toast } = useToast(); const admin = user?.role === "admin" || user?.role === "superadmin"; const [items, setItems] = useState<Payment[]>([]); const [staff, setStaff] = useState<Staff[]>([]); const [advance, setAdvance] = useState({ amount: "", reason: "" }); const [salary, setSalary] = useState({ staff: "", amount: "", period: new Date().toISOString().slice(0, 7), notes: "" }); const [error, setError] = useState("");
  if (admin) return <Navigate to="/management/payroll" replace />;
  const load = async () => { try { const payments = await api.get<{ data: Payment[] }>(admin ? "/staff-payments" : "/staff-payments/my"); setItems(payments.data.data); if (admin) { const users = await api.get<{ data: Staff[] }>("/users"); setStaff(users.data.data.filter((item) => item.role !== "customer" && item.status === "active")); } } catch (error) { setError(error instanceof Error ? error.message : "Unable to load staff finance."); } }; useEffect(() => { void load(); }, [admin]);
  const requestAdvance = async (event: React.FormEvent) => { event.preventDefault(); try { await api.post("/staff-payments/advances", { amount: Number(advance.amount), reason: advance.reason }); setAdvance({ amount: "", reason: "" }); toast("Advance request submitted for review.", "success"); void load(); } catch (error) { setError(error instanceof Error ? error.message : "Unable to submit advance request."); } };
  const recordSalary = async (event: React.FormEvent) => { event.preventDefault(); try { await api.post("/staff-payments/salaries", { ...salary, amount: Number(salary.amount) }); setSalary({ staff: "", amount: "", period: new Date().toISOString().slice(0, 7), notes: "" }); toast("Salary payment recorded.", "success"); void load(); } catch (error) { setError(error instanceof Error ? error.message : "Unable to record salary."); } };
  const updateAdvance = async (id: string, status: string) => { try { await api.patch(`/staff-payments/${id}`, { status }); toast(`Advance marked ${status}.`, "success"); void load(); } catch (error) { setError(error instanceof Error ? error.message : "Unable to update advance."); } };
  return <div className="mx-auto max-w-6xl space-y-6"><div className="rounded-3xl bg-slate-950 p-6 text-white sm:p-8"><div className="flex items-center gap-3"><span className="rounded-2xl bg-white/10 p-3 text-red-300"><Banknote size={24} /></span><div><p className="text-xs font-bold uppercase tracking-widest text-red-300">Staff finance</p><h1 className="mt-1 text-2xl font-extrabold">{admin ? "Salaries & advances" : "My salary advances"}</h1><p className="mt-1 text-sm text-slate-300">{admin ? "Record salary payments and process staff advances." : "Submit an advance request and follow its approval status."}</p></div></div></div>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {admin ? <form onSubmit={recordSalary} className="grid gap-3 rounded-2xl border border-gray-200 bg-white p-5 md:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-bold text-gray-600">Staff member<select required value={salary.staff} onChange={(event) => setSalary({ ...salary, staff: event.target.value })} className="mt-1.5 h-11 w-full rounded-xl border border-gray-200 px-3 text-sm"><option value="">Select staff</option>{staff.map((person) => <option key={person._id} value={person._id}>{person.fullName}</option>)}</select></label><label className="text-xs font-bold text-gray-600">Salary amount (RWF)<input required min="1" type="number" value={salary.amount} onChange={(event) => setSalary({ ...salary, amount: event.target.value })} className="mt-1.5 h-11 w-full rounded-xl border border-gray-200 px-3 text-sm" /></label><label className="text-xs font-bold text-gray-600">Pay period<input required type="month" value={salary.period} onChange={(event) => setSalary({ ...salary, period: event.target.value })} className="mt-1.5 h-11 w-full rounded-xl border border-gray-200 px-3 text-sm" /></label><label className="text-xs font-bold text-gray-600">Notes (optional)<input value={salary.notes} onChange={(event) => setSalary({ ...salary, notes: event.target.value })} className="mt-1.5 h-11 w-full rounded-xl border border-gray-200 px-3 text-sm" /></label><button className="md:col-span-2 xl:col-span-4 rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Record salary payment</button></form> : <form onSubmit={requestAdvance} className="grid gap-3 rounded-2xl border border-gray-200 bg-white p-5 sm:grid-cols-[1fr_2fr_auto]"><input required min="1" type="number" value={advance.amount} onChange={(event) => setAdvance({ ...advance, amount: event.target.value })} placeholder="Advance amount (RWF)" className="h-11 rounded-xl border border-gray-200 px-3 text-sm" /><input required minLength={5} value={advance.reason} onChange={(event) => setAdvance({ ...advance, reason: event.target.value })} placeholder="Reason for the advance request" className="h-11 rounded-xl border border-gray-200 px-3 text-sm" /><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-red-600 px-4 py-3 text-sm font-bold text-white"><Send size={16} />Request advance</button></form>}
    <div className="overflow-x-auto rounded-2xl border border-gray-200 bg-white"><table className="min-w-[700px] w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{admin && <th className="px-5 py-3">Staff</th>}<th className="px-5 py-3">Type</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Details</th><th className="px-5 py-3">Status</th>{admin && <th className="px-5 py-3">Action</th>}</tr></thead><tbody className="divide-y divide-gray-100">{items.map((item) => <tr key={item._id}>{admin && <td className="px-5 py-4 font-semibold">{item.staff?.fullName || "—"}</td>}<td className="px-5 py-4 capitalize">{item.kind}</td><td className="px-5 py-4 font-semibold">{money(item.amount)}</td><td className="px-5 py-4 text-gray-500">{item.period || item.reason || "—"}</td><td className="px-5 py-4"><span className="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-bold capitalize">{item.status}</span></td>{admin && <td className="px-5 py-4">{item.kind === "advance" && item.status !== "paid" && <div className="flex gap-2">{item.status === "pending" && <button onClick={() => void updateAdvance(item._id, "approved")} className="text-xs font-bold text-emerald-700">Approve</button>}<button onClick={() => void updateAdvance(item._id, "paid")} className="text-xs font-bold text-blue-700">Mark paid</button>{item.status === "pending" && <button onClick={() => void updateAdvance(item._id, "rejected")} className="text-xs font-bold text-red-700">Reject</button>}</div>}</td>}</tr>)}{!items.length && <tr><td colSpan={admin ? 6 : 4} className="p-8 text-center text-gray-500">No salary or advance records yet.</td></tr>}</tbody></table></div></div>;
}
