export type ProductionBatchStatus =
  | "Planned"
  | "Ready"
  | "In Progress"
  | "Paused"
  | "Completed"
  | "Cancelled";

export interface ProductionOrderSummary {
  _id: string;
  productionOrderNo: string;
  quantity: number;
  unit: string;
  status:
    | "Draft"
    | "Planned"
    | "Released"
    | "In Production"
    | "Completed"
    | "Cancelled"
    | "On Hold";
  plannedDate?: string;
  expectedCompletionDate?: string;
}

export interface ProductSummary {
  _id: string;
  name: string;
  code?: string;
  productCode?: string;
  sku?: string;
  category?: string;
  unit?: string;
}

export interface FormulaSummary {
  _id: string;
  name: string;
  code?: string;
  formulaCode?: string;
  version: number;
  batchSize?: number;
  batchUnit?: string;
  status?: "Active" | "Inactive";
}

export interface SupervisorSummary {
  _id: string;
  name?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
}

export interface ProductionBatch {
  _id: string;

  batchNo: string;

  productionOrder:
    | string
    | ProductionOrderSummary;

  product:
    | string
    | ProductSummary;

  productName: string;
  productCode: string;

  formula:
    | string
    | FormulaSummary;

  formulaName: string;
  formulaCode: string;
  formulaVersion: number;

  plannedQuantity: number;
  actualQuantity: number;

  /**
   * Remaining quantity on the production order
   * at the time this batch was created/loaded.
   */
  remainingQuantity?: number;

  unit: string;

  status: ProductionBatchStatus;

  /**
   * Generated automatically by backend.
   */
  batchNumber: string;

  lotNumber: string;

  startDate?: string;
  endDate?: string;

  supervisor?:
    | string
    | SupervisorSummary;

  supervisorName: string;

  notes: string;

  createdAt: string;
  updatedAt: string;
}

export interface CreateProductionBatchData {
  productionOrder: string;

  /**
   * Optional.
   * Backend defaults to the remaining quantity.
   */
  plannedQuantity?: number;

  unit?: string;

  /**
   * Create status is controlled by backend.
   * Keep optional for compatibility.
   */
  status?: ProductionBatchStatus;

  /**
   * Batch number is generated by backend.
   */
  batchNumber?: string;

  lotNumber?: string;

  /**
   * Defaults to production order planned date.
   */
  startDate?: string | Date;

  supervisor?: string;

  supervisorName?: string;

  notes?: string;
}

export interface UpdateProductionBatchData {
  plannedQuantity?: number;

  actualQuantity?: number;

  unit?: string;

  status?: ProductionBatchStatus;

  batchNumber?: string;

  lotNumber?: string;

  startDate?: string | Date;

  endDate?: string | Date;

  supervisor?: string;

  supervisorName?: string;

  notes?: string;
}

export interface ProductionBatchStats {
  total: number;
  planned: number;
  ready: number;
  inProgress: number;
  paused: number;
  completed: number;
  cancelled: number;
}