import { Router } from "express";
import StaffPayment from "./staffPayment.model";
import { protect, authorizeRoles, AuthRequest } from "../../middleware/auth.middleware";
import { UserRole } from "../../models/users";

const router = Router();
router.use(protect);
router.get("/my", async (req: AuthRequest, res, next) => { try { const data = await StaffPayment.find({ staff: req.user!.id }).populate("staff", "fullName company department").sort({ createdAt: -1 }); res.json({ data }); } catch (error) { next(error); } });
router.post("/advances", async (req: AuthRequest, res, next) => { try { if (req.user?.role === UserRole.CUSTOMER) return res.status(403).json({ error: { code: "STAFF_ONLY", message: "Only staff can request an advance." } }); const { amount, reason } = req.body; if (!Number.isFinite(Number(amount)) || Number(amount) <= 0 || typeof reason !== "string" || reason.trim().length < 5) return res.status(400).json({ error: { code: "INVALID_ADVANCE", message: "Enter a valid amount and a reason of at least 5 characters." } }); const data = await StaffPayment.create({ staff: req.user!.id, kind: "advance", amount: Number(amount), remainingAmount: Number(amount), reason: reason.trim(), status: "pending" }); res.status(201).json({ data }); } catch (error) { next(error); } });
router.use(authorizeRoles(UserRole.ADMIN));
router.get("/", async (_req, res, next) => { try { const data = await StaffPayment.find().populate("staff", "fullName company department").sort({ createdAt: -1 }); res.json({ data }); } catch (error) { next(error); } });
router.post("/salaries", async (req, res, next) => { try { const { staff, amount, period, notes, paymentDate } = req.body; if (typeof staff !== "string" || !Number.isFinite(Number(amount)) || Number(amount) <= 0 || typeof period !== "string" || !period.trim()) return res.status(400).json({ error: { code: "INVALID_SALARY", message: "Staff member, gross salary and pay period are required." } }); if (await StaffPayment.exists({ staff, kind: "salary", period: period.trim() })) return res.status(409).json({ error: { code: "SALARY_ALREADY_RECORDED", message: "A salary is already recorded for this staff member and pay period." } }); const grossAmount = Number(amount); const advances = await StaffPayment.find({ staff, kind: "advance", status: "paid", remainingAmount: { $gt: 0 } }).sort({ createdAt: 1 }); let remainingGross = grossAmount; let deduction = 0; for (const advance of advances) { const applied = Math.min(remainingGross, Number(advance.remainingAmount || advance.amount)); if (!applied) break; remainingGross -= applied; deduction += applied; advance.remainingAmount = Number(advance.remainingAmount || advance.amount) - applied; advance.status = advance.remainingAmount === 0 ? "deducted" : "paid"; await advance.save(); } const data = await StaffPayment.create({ staff, kind: "salary", amount: grossAmount - deduction, grossAmount, advanceDeduction: deduction, period: period.trim(), notes: typeof notes === "string" ? notes.trim() : "", status: "paid", paymentDate: paymentDate ? new Date(paymentDate) : new Date() }); res.status(201).json({ data }); } catch (error) { next(error); } });
router.patch("/:id", async (req, res, next) => { try { const { status, notes } = req.body; if (!["approved", "rejected", "paid"].includes(status)) return res.status(400).json({ error: { code: "INVALID_STATUS", message: "Invalid payment status." } }); const data = await StaffPayment.findByIdAndUpdate(req.params.id, { $set: { status, ...(typeof notes === "string" ? { notes: notes.trim() } : {}), ...(status === "paid" ? { paymentDate: new Date() } : {}) } }, { new: true }).populate("staff", "fullName company department"); if (!data) return res.status(404).json({ error: { code: "PAYMENT_NOT_FOUND", message: "Staff payment record not found." } }); res.json({ data }); } catch (error) { next(error); } });
export default router;
