import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Clock3, Loader2, Package, Plus, ShoppingCart, Truck } from "lucide-react";
import { Link, useLocation } from "react-router-dom";
import api from "@/services/api";

type Order = { _id: string; orderNumber: string; total: number; status: string; createdAt: string; requestedDeliveryDate?: string; items: { productName: string; quantity: number; unit: string }[] };
const statusMeta: Record<string, { label: string; style: string; icon: typeof Clock3 }> = { confirmed: { label: "Confirmed", style: "bg-blue-50 text-blue-700", icon: CheckCircle2 }, in_production: { label: "In production", style: "bg-amber-50 text-amber-700", icon: Package }, ready_for_delivery: { label: "Ready for delivery", style: "bg-violet-50 text-violet-700", icon: Truck }, delivered: { label: "Delivered", style: "bg-emerald-50 text-emerald-700", icon: CheckCircle2 } };

export default function CustomerOrdersPage() {
  const location = useLocation(); const createdOrder = (location.state as { createdOrder?: string } | null)?.createdOrder; const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await api.get<{ data: Order[] }>("/sales-orders/my"); setOrders(response.data.data || []); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load your orders."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <div className="flex min-h-[50vh] items-center justify-center text-gray-500"><Loader2 className="mr-2 animate-spin" />Loading your orders…</div>;
  return <div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col justify-between gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-red-600">Customer portal</p><h1 className="mt-1 text-3xl font-extrabold text-gray-900">My orders</h1><p className="mt-2 text-sm text-gray-500">Submit product requests, then follow review, production and delivery in one place.</p></div><Link to="/dashboard/orders/new" className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white"><Plus size={17}/>Place an order</Link></header>{createdOrder && <p className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">Order {createdOrder} was submitted to CANA for review.</p>}{error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{!error && orders.length === 0 && <div className="rounded-3xl bg-white p-12 text-center shadow-sm"><ShoppingCart className="mx-auto text-gray-300" size={38} /><h2 className="mt-4 font-bold text-gray-900">No orders yet</h2><p className="mt-2 text-sm text-gray-500">Place an order and CANA will review availability, price and delivery details.</p><Link to="/dashboard/orders/new" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white"><Plus size={16}/>Place an order</Link></div>}<div className="space-y-4">{orders.map((order) => { const meta = statusMeta[order.status] || { label: order.status === "submitted" ? "Submitted for review" : order.status.replaceAll("_", " "), style: order.status === "submitted" ? "bg-slate-100 text-slate-700" : "bg-gray-100 text-gray-700", icon: Clock3 }; const Icon = meta.icon; return <article key={order._id} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-3"><h2 className="font-bold text-gray-900">{order.orderNumber}</h2><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${meta.style}`}><Icon size={13} />{meta.label}</span></div><p className="mt-2 text-sm text-gray-500">Ordered {new Date(order.createdAt).toLocaleDateString("en-RW", { dateStyle: "medium" })}{order.requestedDeliveryDate ? ` · Requested delivery ${new Date(order.requestedDeliveryDate).toLocaleDateString("en-RW", { dateStyle: "medium" })}` : ""}</p></div><p className="text-lg font-bold text-gray-900">{order.total.toLocaleString()} RWF</p></div><div className="mt-5 border-t border-gray-100 pt-4 text-sm text-gray-600">{order.items.map((item) => <p key={`${item.productName}-${item.quantity}`}>{item.productName} <span className="text-gray-400">· {item.quantity} {item.unit}</span></p>)}</div></article>; })}</div></div>;
}
