import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, FileText, Loader2, Package, Plus } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import api from "@/services/api";

type Product = { _id?: string; name?: string; price?: number; unit?: string } | null;
type Quote = { _id: string; status: "Pending" | "Reviewed" | "Approved" | "Rejected"; message?: string; reviewNotes?: string; createdAt: string; salesOrder?: { orderNumber?: string; status?: string }; items: { product: Product; quantity: number; unit: string }[] };

const statusStyle: Record<Quote["status"], string> = { Pending: "bg-amber-100 text-amber-800", Reviewed: "bg-blue-100 text-blue-800", Approved: "bg-emerald-100 text-emerald-800", Rejected: "bg-red-100 text-red-800" };

export default function CustomerQuotationsPage() {
  const { id } = useParams();
  const [quotes, setQuotes] = useState<Quote[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await api.get<{ data: Quote[] }>("/quotations/my"); setQuotes(response.data.data || []); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load quotations."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const selected = useMemo(() => quotes.find((quote) => quote._id === id), [id, quotes]);
  const estimate = (quote: Quote) => quote.items.reduce((sum, item) => sum + (Number(item.product?.price || 0) * Number(item.quantity || 0)), 0);

  if (loading) return <div className="flex min-h-[55vh] items-center justify-center text-gray-500"><Loader2 className="mr-2 animate-spin" />Loading quotations…</div>;
  if (error) return <div className="rounded-2xl bg-red-50 p-5 text-red-700">{error}</div>;
  if (id && !selected) return <div className="rounded-2xl bg-white p-8 text-center shadow-sm"><p className="font-semibold">Quotation not found.</p><Link to="/dashboard/quotations" className="mt-4 inline-flex text-red-600">Back to my quotations</Link></div>;

  if (selected) return <div className="mx-auto max-w-4xl space-y-6"><Link to="/dashboard/quotations" className="inline-flex items-center gap-2 text-sm font-semibold text-gray-600 hover:text-red-600"><ArrowLeft size={16} />All quotations</Link><section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-gray-100 pb-5"><div><p className="text-xs font-bold uppercase tracking-wider text-gray-400">Quotation request</p><h1 className="mt-1 text-2xl font-bold text-gray-900">Quote #{selected._id.slice(-6).toUpperCase()}</h1><p className="mt-1 text-sm text-gray-500">Submitted {new Date(selected.createdAt).toLocaleDateString("en-RW", { dateStyle: "medium" })}</p></div><span className={`rounded-full px-3 py-1.5 text-sm font-semibold ${statusStyle[selected.status]}`}>{selected.status === "Reviewed" ? "Under review" : selected.status}</span></div><div className="mt-5 space-y-3">{selected.items.map((item, index) => <div key={item.product?._id || index} className="flex items-center justify-between rounded-xl bg-gray-50 px-4 py-3"><div className="flex items-center gap-3"><div className="rounded-lg bg-white p-2 text-gray-500"><Package size={17} /></div><div><p className="font-semibold text-gray-900">{item.product?.name || "Unavailable product"}</p><p className="text-sm text-gray-500">{item.quantity} {item.unit}</p></div></div><p className="font-semibold">{(Number(item.product?.price || 0) * item.quantity).toLocaleString()} RWF</p></div>)}</div><div className="mt-5 flex justify-between border-t border-gray-100 pt-5 font-semibold"><span>Estimated value</span><span>{estimate(selected).toLocaleString()} RWF</span></div>{selected.message && <div className="mt-5 rounded-xl bg-gray-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-gray-400">Your note</p><p className="mt-1 text-sm text-gray-700">{selected.message}</p></div>}{selected.reviewNotes && <div className="mt-3 rounded-xl bg-blue-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-blue-700">CANA response</p><p className="mt-1 text-sm text-blue-950">{selected.reviewNotes}</p></div>}{selected.salesOrder?.orderNumber && <div className="mt-3 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900">This quotation is now sales order <strong>{selected.salesOrder.orderNumber}</strong>.</div>}</section></div>;

  return <div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-medium text-red-600">Customer portal</p><h1 className="text-3xl font-bold text-gray-900">My quotations</h1><p className="mt-1 text-sm text-gray-500">Follow each request from submission to order.</p></div><Link to="/cana-paints/request-quote" className="inline-flex items-center justify-center gap-2 rounded-xl bg-red-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17} />Request a quote</Link></header>{quotes.length === 0 ? <div className="rounded-3xl bg-white p-12 text-center shadow-sm"><FileText className="mx-auto text-gray-300" size={36} /><h2 className="mt-4 font-bold">No quotations yet</h2><p className="mt-1 text-sm text-gray-500">Start by selecting the products you need.</p></div> : <div className="grid gap-4 md:grid-cols-2">{quotes.map((quote) => <Link key={quote._id} to={`/dashboard/quotations/${quote._id}`} className="rounded-2xl border border-gray-200 bg-white p-5 transition hover:border-red-200 hover:shadow-sm"><div className="flex justify-between gap-3"><div><p className="font-bold text-gray-900">Quote #{quote._id.slice(-6).toUpperCase()}</p><p className="mt-1 text-sm text-gray-500">{new Date(quote.createdAt).toLocaleDateString("en-RW", { dateStyle: "medium" })}</p></div><span className={`h-fit rounded-full px-2.5 py-1 text-xs font-semibold ${statusStyle[quote.status]}`}>{quote.status === "Reviewed" ? "Under review" : quote.status}</span></div><p className="mt-4 truncate text-sm text-gray-600">{quote.items.map((item) => item.product?.name || "Product").join(", ")}</p><div className="mt-4 flex justify-between border-t border-gray-100 pt-4 text-sm"><span className="text-gray-500">{quote.items.length} product{quote.items.length === 1 ? "" : "s"}</span><span className="font-bold">{estimate(quote).toLocaleString()} RWF</span></div></Link>)}</div>}</div>;
}
