import { ArrowRight, Building2, Eye, Factory, Lightbulb, ShieldCheck, Target, Users } from "lucide-react";
import { Link } from "react-router-dom";

const values = [
  { title: "Integrity", description: "We work with honesty, accountability and clear communication.", icon: ShieldCheck },
  { title: "Excellence", description: "We hold our products, services and delivery to a professional standard.", icon: Target },
  { title: "Innovation", description: "We improve practical solutions as customer and project needs change.", icon: Lightbulb },
  { title: "Customer focus", description: "We listen carefully and build solutions around the work that matters.", icon: Users },
];

export default function About() {
  return (
    <main className="bg-white text-slate-950">
      <section className="border-y border-slate-200 bg-white">
        <div className="mx-auto grid max-w-7xl gap-6 px-5 py-9 sm:px-8 sm:py-12 lg:grid-cols-[1fr_.8fr] lg:items-end lg:px-8">
          <div><p className="cana-section-kicker">CANAN Business Group</p><h1 className="mt-1 max-w-3xl text-4xl font-extrabold tracking-[-.055em] sm:text-5xl">Built on quality. Designed for practical value.</h1></div>
          <div><p className="max-w-xl text-sm leading-6 text-slate-600 sm:text-base">CANA brings together dependable paint products and practical site services for homes, businesses and projects across Rwanda.</p><div className="mt-6 flex flex-wrap gap-2"><Link to="/contact" className="inline-flex h-10 items-center gap-2 rounded-lg bg-slate-950 px-4 text-sm font-bold text-white transition hover:bg-red-700">Work with CANA <ArrowRight size={16} /></Link><Link to="/projects" className="inline-flex h-10 items-center rounded-lg border border-slate-300 px-4 text-sm font-bold text-slate-800 transition hover:border-slate-950">View projects</Link></div></div>
        </div>
      </section>

      <section className="mx-auto grid max-w-7xl gap-6 px-5 py-8 sm:px-8 sm:py-10 lg:grid-cols-[.78fr_1.22fr] lg:px-8"><div><p className="cana-section-kicker">Who we are</p><h2 className="mt-1 text-3xl font-extrabold tracking-[-.04em]">One group. Practical capability.</h2></div><div className="max-w-2xl"><p className="text-base leading-7 text-slate-700">CANA is a Rwandan business group providing quality paint products and professional services that help customers complete work with confidence.</p><p className="mt-4 text-sm leading-6 text-slate-500">Across every division, we share a commitment to reliability, thoughtful service and consistent results.</p></div></section>

      <section className="border-y border-slate-200 bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 sm:py-10 lg:px-8"><div><p className="cana-section-kicker">Our divisions</p><h2 className="mt-1 text-3xl font-extrabold tracking-[-.04em]">Two divisions. One standard.</h2></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-red-50 text-red-700"><Factory size={19} /></span><p className="mt-5 text-xs font-extrabold uppercase tracking-[.15em] text-slate-500">Division 01</p><h3 className="mt-2 text-2xl font-extrabold tracking-tight">CANA Paints</h3><p className="mt-3 max-w-lg text-sm leading-6 text-slate-600">Quality paint products, colour solutions and finishing support for residential and commercial work.</p><Link to="/cana-paints/products" className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-slate-950 hover:text-red-700">Explore CANA Paints <ArrowRight size={15} /></Link></article><article className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 text-slate-800"><Building2 size={19} /></span><p className="mt-5 text-xs font-extrabold uppercase tracking-[.15em] text-slate-500">Division 02</p><h3 className="mt-2 text-2xl font-extrabold tracking-tight">CANA Services</h3><p className="mt-3 max-w-lg text-sm leading-6 text-slate-600">Scaffolding, transport and practical services that keep active projects moving.</p><Link to="/cana-services/scaffolds" className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-slate-950 hover:text-red-700">Explore CANA Services <ArrowRight size={15} /></Link></article></div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-8 sm:px-8 sm:py-10 lg:px-8"><div><p className="cana-section-kicker">Our direction</p><h2 className="mt-1 text-3xl font-extrabold tracking-[-.04em]">The standards behind our work.</h2></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><article className="rounded-2xl bg-slate-950 p-5 text-white sm:p-6"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/10 text-white"><Target size={19} /></span><p className="mt-5 text-xs font-extrabold uppercase tracking-[.15em] text-white/55">Our mission</p><h3 className="mt-2 text-2xl font-extrabold tracking-tight">Deliver practical value through quality and service.</h3><p className="mt-3 text-sm leading-6 text-white/65">We provide dependable products and professional services that solve real customer needs.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 text-slate-800"><Eye size={19} /></span><p className="mt-5 text-xs font-extrabold uppercase tracking-[.15em] text-slate-500">Our vision</p><h3 className="mt-2 text-2xl font-extrabold tracking-tight">Build a trusted, diversified African business group.</h3><p className="mt-3 text-sm leading-6 text-slate-600">We aim to be recognised for quality, innovation, professionalism and lasting impact.</p></article></div></section>

      <section className="border-y border-slate-200 bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 sm:py-10 lg:px-8"><div><p className="cana-section-kicker">Our values</p><h2 className="mt-1 text-3xl font-extrabold tracking-[-.04em]">How we show up.</h2></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{values.map(({ title, description, icon: Icon }) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-4"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-red-50 text-red-700"><Icon size={17} /></span><h3 className="mt-5 font-extrabold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></article>)}</div></div></section>

      <section className="bg-slate-950 py-9 text-white sm:py-12"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 sm:px-8 md:flex-row md:items-center md:justify-between lg:px-8"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-red-400">Start a conversation</p><h2 className="mt-2 text-2xl font-extrabold tracking-tight">Tell us what you need.</h2></div><Link to="/contact" className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-red-700 px-4 text-sm font-bold text-white transition hover:bg-red-600">Contact CANA <ArrowRight size={16} /></Link></div></section>
    </main>
  );
}
