import logo from "@/assets/logocanan.png";

export type PrintDetail = { label: string; value?: string | number | null };
export type PrintTable = { headers: string[]; rows: Array<Array<string | number | null | undefined>> };

const escapeHtml = (value: string | number | null | undefined) => String(value ?? "—").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] || character);

/** Opens a branded, self-contained operational record that can be printed or saved as PDF. */
export function printCanaDocument({ title, reference, status, details = [], table, notes }: { title: string; reference: string; status?: string; details?: PrintDetail[]; table?: PrintTable; notes?: string }) {
  const popup = window.open("", "_blank", "width=900,height=800");
  if (!popup) return;
  const issued = new Date().toLocaleString("en-RW", { dateStyle: "medium", timeStyle: "short" });
  const detailRows = details.map((detail) => `<div class="detail"><span>${escapeHtml(detail.label)}</span><strong>${escapeHtml(detail.value)}</strong></div>`).join("");
  const tableHtml = table ? `<section class="section"><h2>Record details</h2><table><thead><tr>${table.headers.map((header) => `<th>${escapeHtml(header)}</th>`).join("")}</tr></thead><tbody>${table.rows.map((row) => `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`).join("")}</tbody></table></section>` : "";
  popup.document.write(`<!doctype html><html><head><title>${escapeHtml(title)} · ${escapeHtml(reference)}</title><style>body{font-family:Arial,sans-serif;color:#172033;margin:0;background:#f1f5f9}.page{width:760px;min-height:900px;box-sizing:border-box;margin:28px auto;background:#fff;padding:46px}.head{display:flex;justify-content:space-between;gap:24px;border-bottom:3px solid #c8242f;padding-bottom:20px}.brand{display:flex;align-items:center;gap:13px}.logo{width:76px;max-height:58px;object-fit:contain}.name{font-size:22px;font-weight:800}.muted{font-size:11px;line-height:1.65;color:#64748b}.title{text-align:right}.title h1{margin:0;font-size:26px;letter-spacing:.3px}.ref{margin-top:7px;font-size:12px;font-weight:700;color:#334155}.status{display:inline-block;margin-top:8px;border-radius:999px;background:#fef2f2;color:#b91c1c;padding:4px 9px;font-size:10px;font-weight:700;letter-spacing:.7px;text-transform:uppercase}.section{margin-top:28px}.section h2{margin:0 0 11px;color:#c8242f;font-size:10px;letter-spacing:1.3px;text-transform:uppercase}.details{display:grid;grid-template-columns:1fr 1fr;gap:0 24px;border:1px solid #e2e8f0;border-radius:9px;padding:4px 14px}.detail{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid #edf2f7;padding:11px 0;font-size:12px}.detail:nth-last-child(-n+2){border-bottom:0}.detail span{color:#64748b}.detail strong{text-align:right;font-weight:600}table{width:100%;border-collapse:collapse;font-size:12px}th{background:#172033;color:#fff;text-align:left;padding:10px;font-size:10px;letter-spacing:.7px;text-transform:uppercase}td{padding:11px 10px;border-bottom:1px solid #e2e8f0;vertical-align:top}.note{margin-top:28px;border-left:3px solid #c8242f;background:#fff7f7;padding:13px 15px;font-size:12px;line-height:1.6}.foot{display:flex;justify-content:space-between;gap:18px;margin-top:48px;border-top:1px solid #e2e8f0;padding-top:14px;font-size:10px;color:#94a3b8}@media print{body{background:#fff}.page{width:auto;margin:0;padding:34px}.detail:nth-last-child(-n+2){border-bottom:0}}</style></head><body><main class="page"><header class="head"><div class="brand"><img class="logo" src="${logo}" alt="CANA logo"><div><div class="name">CANA Group</div><div class="muted">Quality · Service · Solutions<br>Kigali, Rwanda · +250 789 408 367</div></div></div><div class="title"><h1>${escapeHtml(title)}</h1><div class="ref">Reference: ${escapeHtml(reference)}</div>${status ? `<div class="status">${escapeHtml(status)}</div>` : ""}<div class="muted">Generated: ${escapeHtml(issued)}</div></div></header><section class="section"><h2>Document summary</h2><div class="details">${detailRows}</div></section>${tableHtml}${notes ? `<div class="note"><strong>Notes</strong><br>${escapeHtml(notes)}</div>` : ""}<footer class="foot"><span>System-generated CANA operational record</span><span>Keep with the related inventory or production file.</span></footer></main><script>window.onload=()=>window.print()</script></body></html>`);
  popup.document.close();
}
