import { useEffect, useMemo, useState } from "react";
import { ArrowRight, FileText, PackageCheck, ReceiptText, RefreshCw, ShoppingCart } from "lucide-react";
import { Link } from "react-router-dom";
import api from "@/services/api";

type Order = { _id: string; status: string };
type Quote = { _id: string; status: string };
type Invoice = { _id: string; balance?: number; status?: string };
const money = (value: number) => Number(value || 0).toLocaleString("en-RW", { maximumFractionDigits: 0 });

function Metric({ title, value, icon: Icon }: { title: string; value: string | number; icon: typeof FileText }) {
  return <article className="cana-panel p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{title}</p><p className="mt-1 text-2xl font-extrabold tracking-tight text-slate-950">{value}</p></div><span className="rounded-lg bg-slate-100 p-2 text-slate-700"><Icon size={17} /></span></div></article>;
}
function Queue({ number, title, to }: { number: number; title: string; to: string }) {
  return <Link to={to} className="flex items-center gap-3 rounded-lg border border-slate-200 px-3 py-2.5 transition hover:bg-slate-50"><strong className="flex h-8 min-w-8 items-center justify-center rounded-md bg-slate-950 text-xs text-white">{number}</strong><span className="flex-1 text-sm font-bold text-slate-900">{title}</span><ArrowRight size={15} className="text-slate-400" /></Link>;
}

export default function SalesWorkspacePage() {
  const [orders, setOrders] = useState<Order[]>([]); const [quotes, setQuotes] = useState<Quote[]>([]); const [invoices, setInvoices] = useState<Invoice[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { try { setLoading(true); setError(""); const [orderData, quoteData, invoiceData] = await Promise.all([api.get<{ data: Order[] }>("/sales-orders"), api.get<{ data: Quote[] }>("/quotations"), api.get<{ data: Invoice[] }>("/billing/invoices")]); setOrders(orderData.data.data || []); setQuotes(quoteData.data.data || []); setInvoices(invoiceData.data.data || []); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load sales activity."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const summary = useMemo(() => ({ quotes: quotes.filter((item) => item.status.toLowerCase() === "pending").length, submitted: orders.filter((item) => item.status === "submitted").length, ready: orders.filter((item) => item.status === "ready_for_delivery").length, outstanding: invoices.filter((item) => item.status !== "void").reduce((sum, item) => sum + Number(item.balance || 0), 0) }), [orders, quotes, invoices]);
  return <div className="mx-auto max-w-6xl space-y-4"><header className="flex flex-col justify-between gap-3 border-b border-slate-200 pb-4 sm:flex-row sm:items-center"><div><p className="cana-section-kicker">Sales & finance</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight text-slate-950">Sales overview</h1></div><div className="flex gap-2"><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50"><RefreshCw size={15} className={loading ? "animate-spin" : ""} />Refresh</button><Link to="/management/sales/orders" className="inline-flex items-center gap-2 rounded-lg bg-slate-950 px-3 py-2 text-sm font-bold text-white hover:bg-slate-800"><ShoppingCart size={15} />Orders</Link></div></header>{error && <p className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Quotation requests" value={loading ? "—" : summary.quotes} icon={FileText} /><Metric title="Customer orders" value={loading ? "—" : summary.submitted} icon={ShoppingCart} /><Metric title="Ready to deliver" value={loading ? "—" : summary.ready} icon={PackageCheck} /><Metric title="Outstanding" value={loading ? "—" : `${money(summary.outstanding)} RWF`} icon={ReceiptText} /></section><section className="grid gap-3 lg:grid-cols-2"><section className="cana-panel p-4"><h2 className="text-base font-extrabold text-slate-950">Priority queue</h2><div className="mt-3 space-y-2"><Queue number={summary.quotes} title="Review quotation requests" to="/management/quotations" /><Queue number={summary.submitted} title="Confirm customer orders" to="/management/sales/orders" /><Queue number={summary.ready} title="Arrange delivery or pickup" to="/management/sales/fulfilment" /></div></section><section className="cana-panel p-4"><h2 className="text-base font-extrabold text-slate-950">Sales tools</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><Link to="/management/quotations" className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-bold text-slate-800 hover:bg-slate-50">Quotations</Link><Link to="/management/sales/orders" className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-bold text-slate-800 hover:bg-slate-50">Sales orders</Link><Link to="/management/billing" className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-bold text-slate-800 hover:bg-slate-50">Invoices & payments</Link><Link to="/management/sales/proforma" className="rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-bold text-slate-800 hover:bg-slate-50">Proformas</Link></div></section></section></div>;
}
